<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\PanelManager\Version.props" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <AssemblyName>PanelManagerSetup</AssemblyName>
    <RootNamespace>PanelManager.Installer</RootNamespace>
    <ApplicationIcon>..\PanelManager\Resources\AppIcon\appicon.ico</ApplicationIcon>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    <TrimmerDefaultAction>link</TrimmerDefaultAction>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
    <IlcGenerateMstatFile>false</IlcGenerateMstatFile>
    <IlcGenerateDgmlFile>false</IlcGenerateDgmlFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Runtime.InteropServices.EnableConsumingManagedCodeFromNativeHosting" Value="true" />
    <EmbeddedResource Include="Dependencies\PawnIO\PawnIO_setup.exe" LogicalName="PawnIO_setup.exe" />
  </ItemGroup>

  <Target Name="VerifyPawnIoResource" BeforeTargets="BeforeBuild">
    <GetFileHash Files="$(MSBuildThisFileDirectory)Dependencies\PawnIO\PawnIO_setup.exe" Algorithm="SHA256">
      <Output TaskParameter="Hash" PropertyName="PawnIoResourceHash" />
    </GetFileHash>
    <Error Condition="'$(PawnIoResourceHash)' != 'A3A46226C5E2824F4CDD42BE0EECBABFC672C86F7889710F5AB1E6AD385B47A0'" Text="PawnIO resource does not match LibreHardwareMonitor v0.9.6." />
  </Target>

  <ItemGroup Condition="'$(PayloadZip)' != '' And Exists('$(PayloadZip)')">
    <EmbeddedResource Include="$(PayloadZip)" LogicalName="payload.7z" />
  </ItemGroup>

  <ItemGroup Condition="'$(SevenZipExe)' != '' And Exists('$(SevenZipExe)')">
    <EmbeddedResource Include="$(SevenZipExe)" LogicalName="7zr.exe" />
  </ItemGroup>
</Project>
